### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by GuzekAlan** [kraleppa/vscode-ekstraklasa#5]
I've recently encountered problem with Ekstraklasa extension. I've got this error message in output:

```
2024-06-28 17:16:30.762 [warning] TextEditor is closed/disposed
2024-06-28 17:16:37.700 [warning] TextEditor is closed/disposed
2024-06-28 17:17:33.811 [warning] TextEditor is closed/disposed
2024-06-28 17:17:34.914 [error] TypeError: Cannot read properties of null (reading 'map')
    at parseLastResults (/Users/alanguzek/.vscode/extensions/kraleppa.vscode-ekstraklasa-1.0.0/out/extension.js:104:24)
    at standingComponent (/Users/alanguzek/.vscode/extensions/kraleppa.vscode-ekstraklasa-1.0.0/out/extension.js:97:13)
    at /Users/alanguzek/.vscode/extensions/kraleppa.vscode-ekstraklasa-1.0.0/out/extension.js:75:40
    at Array.map (<anonymous>)
    at parseStandings (/Users/alanguzek/.vscode/extensions/kraleppa.vscode-ekstraklasa-1.0.0/out/extension.js:75:22)
    at getWebviewContent (/Users/alanguzek/.vscode/extensions/kraleppa.vscode-ekstraklasa-1.0.0/out/extension.js:68:13)
    at showView (/Users/alanguzek/.vscode/extensions/kraleppa.vscode-ekstraklasa-1.0.0/out/extension.js:41:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    
```
    
and I have empty screen on my VSCode
    
![image](https://github.com/kraleppa/vscode-ekstraklasa/assets/24592312/a149afbe-249d-40ad-b14c-1f2f068469e2)

**Comment by szarbartosz** [comment]
Due to the ekstraklasa points reset at the end of the round, scraper adjustment was required - it was addressed within https://github.com/szarbartosz/ekstraklasa-scraper/commit/32729c084d7976899ee1151f7cd742bc1f0ef96b

Our favourite vs code extension works like a charm again! (It even contains the spoiler for the end of the next round - Puszcza Niepołomice on the 1st place 🌲 )

<img width="841" alt="image" src="https://github.com/kraleppa/vscode-ekstraklasa/assets/48298481/3611ca4d-40a0-4ce0-aed8-f098e9dc8719">

**Comment by kraleppa** [comment]
Thanks, @szarbartosz for a fix 🌲

Closing this issue as done
